packages/stylelint-plugin-slds/package.json, packages/stylelint-plugin-slds/rollup.config.js
- Removed duplicate package
- Added rollup so that we don't get warning for build script.
=> Adding a minor fix

packages/stylelint-plugin-slds/src/reports/json-to-sarif.ts
=> fix: fix duplicate rules in sarif

packages/slds-linter/src/index.ts
=> Bring up help on invalid command

packages/slds-linter/src/commands/report.ts, packages/slds-linter/src/services/report-generator.ts, packages/slds-linter/src/types/index.ts, packages/slds-linter/src/workers/eslint.worker.ts, packages/slds-linter/src/workers/stylelint.worker.ts
=> fix: add endColumn

packages/slds-linter/README.md, packages/slds-linter/src/commands/lint-components.ts, packages/slds-linter/src/commands/lint-styles.ts, packages/slds-linter/src/commands/lint.ts, packages/slds-linter/src/commands/report.ts, packages/slds-linter/src/index.ts, packages/slds-linter/src/utils/cli-args.ts
- resolving version, description from package.json
- removed default value for configs to avoid printing path
=> fix(cli): corrected version string and command

packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/slds-linter/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.0.12-alpha.1

packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/slds-linter/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.0.12-alpha.2

packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/slds-linter/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.0.12-alpha.4

packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/slds-linter/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.0.12-alpha.5

packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/slds-linter/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.0.12-alpha.6

packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/slds-linter/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.0.13-alpha.0

packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/slds-linter/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.0.13-alpha.1

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.0

packages/eslint-plugin-slds/.eslintrc.yml
=> fix: change rule names

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.1

README.md
[W-17832330](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000029pKF6YAM/view)
[Drafting doc](https://docs.google.com/document/d/1rLOMKH-dFF3XjqSVX8eUwJOyCr7aeSjB2Py5OM00hs8/edit?tab=t.0)
=> implement CX edits to README.md

README.md, packages/cli/src/utils/nodeVersionUtil.ts
corrected logic to use semver satisfies for node range "^18.20.0 || >=20.10.0"
=> fix(cli): corrected node version check logic

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.2-alpha.0

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.2

README.md, demo/com/CORE/demoComponent copy.cmp, demo/com/CORE/demoComponent.cmp, demo/com/PDG/demoComponent copy.cmp, demo/com/PDG/demoComponent.cmp, demo/com/X/demoComponent copy.cmp, demo/com/X/demoComponent.cmp, demo/com/Y/demoComponent copy.cmp, demo/com/Y/demoComponent.cmp, demo/test/aura/demoComponent copy.cmp, demo/test/aura/demoComponent.cmp, demo/test/aura/demoComponent.css, demo/test/aura/demoComponentController.js, demo/test/aura/demoComponentHelper.js, demo/test/lwc/demoComponent.cmp, demo/test/valueToStylinghook.sldsplus.html, packages/cli/README.md, packages/cli/src/services/file-scanner.ts, packages/cli/src/utils/cli-args.ts
=> Files directory

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.3-alpha.1

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.3

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.4-alpha.0

demo/small-set/modal-close-button.html, packages/eslint-plugin-slds/src/rules/modal-close-button-issue.ts, packages/eslint-plugin-slds/test/rules/modal-close-button-issue.test.js, packages/stylelint-plugin-slds/src/utils/color-lib-utils.ts, packages/stylelint-plugin-slds/tests/rules/no-hardcoded-values-slds1/no-hardcoded-values-slds1.spec.ts, packages/stylelint-plugin-slds/tests/rules/no-hardcoded-values-slds2/no-hardcoded-values-slds2.spec.ts
- Check whether the given color and recommended color are the same before calculating the distance
- Added modal-close-button.html for testing this accessibility bug
- Changed test case as per the above #1 item.
=> Adding a minor change for color util

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.4-alpha.2

demo/small-set/modal-close-button.html, packages/eslint-plugin-slds/src/rules/modal-close-button-issue.ts, packages/eslint-plugin-slds/test/rules/modal-close-button-issue.test.js
Signed-off-by: Kishore Nemalipuri <lnemalipuri@salesforce.com>
(cherry picked from commit eb7abc1c4934a149a745ac224044bec3d3aeb980)
=> Adding fixes based on the current understanding

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.4-alpha.3

demo/W-17909316.css, demo/shorthand-props.css, packages/stylelint-plugin-slds/src/rules/lwc-token-to-slds-hook/index.ts, packages/stylelint-plugin-slds/tests/rules/lwc-to-slds-token/lwc-to-slds-token.spec.ts, yarn.lock
- corrected logic to handle shorthand prop
- added test css file
- corrected logic to detect already fixed lwc
- added logic to handle when lwc used in fallback
W-17909316
=> fix(lwc-slds):entire value is a shorthand prop replaced by slds token

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.4

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.5

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/metadata/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.6

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.7-alpha.0

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.7-alpha.1

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.8

package.json, scripts/comment-release-prs.js, scripts/generate-release-notes.js, scripts/release.js, yarn.lock
- Introduced `generate-release-notes.js` to create detailed release notes based on commit messages.
- Added `comment-release-prs.js` to comment on PRs included in the latest release.
- Updated `release.js` to integrate the new release notes generation and PR commenting functionality.
- Updated dependencies in `package.json` and `yarn.lock` to include new packages required for the scripts.
=> chore: add scripts for generating release notes and commenting on PRs

scripts/comment-release-prs.js
- Updated `commentOnPRs` function to add comments and labels to PRs included in the latest release.
=> chore: updated release script add PR  labels

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.1.9

docs/release-process.md, scripts/comment-release-prs.js
- Created a new document outlining the steps for creating a new release, including preparation steps, usage of the release script, available options, and verification processes.
- Included instructions for handling automated and manual tasks during the release process.
=> docs: add release process documentation

package.json, packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json, scripts/release.js
=> Release 0.2.0-alpha.0

package.json, packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.2.0-alpha.1

package.json, packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.2.0-alpha.2

package.json, packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json, scripts/release.js, yarn.lock
This PR fixes the release script that was failing on the main branch after Yarn workspace changes. The main issue was that the script was using the outdated yarn workspaces info --json command which is not compatible with newer Yarn versions.
=> @W-18549731: Release Script Fix for Yarn Workspace Changes

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.2.0-alpha.4

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.2.0-alpha.5

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.2.0

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.2.1-alpha.0

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.2.1

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json, yarn.lock
=> Release 0.2.2-alpha.0

demo/small-set/deprecated-tokens-slds1.css, demo/small-set/enforce-sds-to-slds-hooks.css, demo/small-set/no-slds-var-without-fallback.css, demo/small-set/slds-class-override.css, packages/stylelint-plugin-slds/src/rules/enforce-bem-usage/index.ts, packages/stylelint-plugin-slds/src/rules/enforce-sds-to-slds-hooks/index.ts, packages/stylelint-plugin-slds/src/rules/lwc-token-to-slds-hook/index.ts, packages/stylelint-plugin-slds/src/rules/no-calc-function/index.ts, packages/stylelint-plugin-slds/src/rules/no-deprecated-slds-classes/index.ts, packages/stylelint-plugin-slds/src/rules/no-deprecated-tokens-slds1/index.ts, packages/stylelint-plugin-slds/src/rules/no-hardcoded-value/noHardcodedValue.rule.ts, packages/stylelint-plugin-slds/src/rules/no-important-tag/index.ts, packages/stylelint-plugin-slds/src/rules/no-slds-class-overrides/index.ts, packages/stylelint-plugin-slds/src/rules/no-slds-var-without-fallback/index.ts, packages/stylelint-plugin-slds/src/rules/no-unsupported-hooks-slds2/index.ts, packages/stylelint-plugin-slds/src/utils/decl-utils.ts, packages/stylelint-plugin-slds/src/utils/prop-utills.ts, packages/stylelint-plugin-slds/src/utils/selector-utils.ts, packages/stylelint-plugin-slds/tests/rules/no-slds-var-without-fallback/no-slds-var-without-fallback.spec.ts, yarn.lock
This PR addresses multiple issues with SLDS stylelint rules to improve validator parity and reduce false positives. The changes focus on enhancing the accuracy and reliability of SLDS class validation, token fallback detection, and selector-based rule processing.
- **Selector Utilities**: Added null check in selector utilities to avoid target properties support issues in selector-based rules
- **SLDS Fallback Rules**: Corrected `slds-no-fallback` rule and deprecated SLDS2 token rules for better accuracy
- **Class Override Detection**: Modified logic to report only the last SLDS class in a selector as override, reducing false positives
- **Token Filtering**: Enhanced fallback detection to stop reporting:
- `--lwc` tokens in fallback scenarios
- SDS tokens in fallback scenarios
- **Function …
=> Linter rule fixes to maintain parity with SLDS Validator

demo/small-set/box-shadow-hooks.css, demo/small-set/font-props.css, demo/small-set/font-short-hand.css, demo/small-set/hardcoded-values.css, packages/stylelint-plugin-slds/src/rules/no-hardcoded-value/handlers/boxShadowHandler.ts, packages/stylelint-plugin-slds/src/rules/no-hardcoded-value/handlers/colorHandler.ts, packages/stylelint-plugin-slds/src/rules/no-hardcoded-value/handlers/densityHandler.ts, packages/stylelint-plugin-slds/src/rules/no-hardcoded-value/handlers/fontHandler.ts, packages/stylelint-plugin-slds/src/rules/no-hardcoded-value/noHardcodedValue.rule.ts, packages/stylelint-plugin-slds/src/utils/boxShadowValueParser.ts, packages/stylelint-plugin-slds/src/utils/color-utils.ts, packages/stylelint-plugin-slds/src/utils/decl-utils.ts, packages/stylelint-plugin-slds/src/utils/density-utils.ts, packages/stylelint-plugin-slds/src/utils/fontValueParser.ts, packages/stylelint-plugin-slds/src/utils/prop-utills.ts, packages/stylelint-plugin-slds/src/utils/property-matcher.ts, packages/stylelint-plugin-slds/src/utils/report-utils.ts, packages/stylelint-plugin-slds/src/utils/rule-message-utils.ts, packages/stylelint-plugin-slds/src/utils/styling-hook-utils.ts, packages/stylelint-plugin-slds/src/utils/util.ts, packages/stylelint-plugin-slds/src/utils/value-utils.ts, packages/stylelint-plugin-slds/tests/rules/no-hardcoded-values-slds1/no-hardcoded-values-slds1.spec.ts, packages/stylelint-plugin-slds/tests/rules/no-hardcoded-values-slds2/no-hardcoded-values-slds2.spec.ts, packages/stylelint-plugin-slds/tests/utils/boxShadowValueParser.test.ts, packages/stylelint-plugin-slds/tests/utils/fontValueParser.spec.ts
- added support to handle hardcoded values for font-weight
- added logic to handle font short hand
- refactor logic for no-hardcoded-values rule for better modularity
=> Report Hardcoded font weight 

packages/stylelint-plugin-slds/.stylelintrc.yml, yarn.lock
corrected .stylelintrc.yml to be compatible with latest version of stylelint
=> chore: support latest version of stylelint

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.2.2

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json
=> Release 0.2.2-alpha-2-alpha.0

.gitignore, .yarnrc, .yarnrc.yml, Procfile, app.json, package.json, packages/cli/jest.config.ts, packages/cli/package.json, packages/cli/tests/executor.test.ts, packages/cli/tests/file-scanner.test.ts, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/jest.config.ts, packages/stylelint-plugin-slds/package.json, scripts/consolidate-coverage.js, scripts/generate-index.js, scripts/heroku-build.js, scripts/heroku-start.js, scripts/sarif-to-html-report.js, scripts/validate-sarif.js, yarn.lock
- Updated `.yarnrc.yml` to include `npmRegistryServer` and `enableImmutableInstalls`.
- Introduced `app.json` for Heroku deployment configuration.
- Updated `package.json` scripts for improved testing and Heroku integration.
- Added new `Procfile` for Heroku to specify the web process.
- Enhanced `jest.config.ts` for better ESM support in CLI package.
- Script to generate html view for sarif report
=> chore: configure pr review app

package.json, packages/eslint-plugin-slds/gulpfile.mjs, packages/stylelint-plugin-slds/gulpfile.js, scripts/release.js, yarn.lock
- updated release script to prompt for target persona
- replacing import statement during build based on build params
=> chore: created script to override import path based on build params

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json, yarn.lock
=> Release 0.3.1-internal-beta.3

packages/eslint-plugin-slds/src/rules/enforce-bem-usage.ts, packages/eslint-plugin-slds/src/rules/modal-close-button-issue.ts, packages/eslint-plugin-slds/src/rules/no-deprecated-classes-slds2.ts, packages/eslint-plugin-slds/test/rules/enforce-bem-usage.test.js, packages/eslint-plugin-slds/test/rules/modal-close-button-issue.test.js, packages/eslint-plugin-slds/test/rules/no-deprecated-classes-slds2.test.js, packages/stylelint-plugin-slds/src/rules/enforce-component-hook-naming-convention/index.ts, packages/stylelint-plugin-slds/src/rules/enforce-sds-to-slds-hooks/index.ts, packages/stylelint-plugin-slds/src/rules/no-slds-private-var/index.ts, packages/stylelint-plugin-slds/src/utils/report-utils.ts, packages/stylelint-plugin-slds/tests/rules/no-hardcoded-values-slds1/no-hardcoded-values-slds1.spec.ts, packages/stylelint-plugin-slds/tests/rules/no-hardcoded-values-slds2/no-hardcoded-values-slds2.spec.ts, packages/stylelint-plugin-slds/tests/rules/no-slds-private-var/no-slds-private-var.spec.ts
Remove suggestions 
Related: Issue #2.
npx eslint
=> fix: remove suggestions

packages/eslint-plugin-slds/README.md
Refer: https://docs.google.com/document/d/1--eFUh5YkTXL64SwVfx5HwkGpFhc6GkDfre2qMz1ZtU/edit?tab=t.0
=> docs: Update eslint plugin README with usage details

packages/eslint-plugin-slds/README.md
* docs: Update eslint plugin README with usage details
=> docs: Update eslint plugin README with usage details (#235)

packages/eslint-plugin-slds/src/config/rule-messages.yml, packages/eslint-plugin-slds/src/index.ts, packages/eslint-plugin-slds/src/rules/v9/lwc-token-to-slds-hook.ts, packages/eslint-plugin-slds/test/rules/lwc-token-to-slds-hook.test.js, packages/stylelint-plugin-slds/stylelint.rules.internal.json
=> feat: lwc-token-to-slds-hook Eslint v9

packages/cli/package.json, packages/eslint-plugin-slds/package.json, packages/stylelint-plugin-slds/package.json, yarn.lock
=> Release 0.5.2-internal

packages/eslint-plugin-slds/src/rules/v9/lwc-token-to-slds-hook.ts, packages/eslint-plugin-slds/src/rules/v9/no-hardcoded-values/handlers/boxShadowHandler.ts, packages/eslint-plugin-slds/src/rules/v9/no-hardcoded-values/handlers/colorHandler.ts, packages/eslint-plugin-slds/src/rules/v9/no-hardcoded-values/handlers/densityHandler.ts, packages/eslint-plugin-slds/src/rules/v9/no-hardcoded-values/handlers/fontHandler.ts, packages/eslint-plugin-slds/src/utils/css-utils.ts, packages/eslint-plugin-slds/test/rules/lwc-token-to-slds-hook.test.js
Formatting suggestions to multiple lines for better readabaility and consisteny with earlier released verisons
=> Formatting suggestions to multiple lines for better readabaility and consisteny with earlier released verisons

packages/eslint-plugin-slds/README.md, packages/eslint-plugin-slds/eslint.rules.json, packages/eslint-plugin-slds/package.json, packages/eslint-plugin-slds/src/config/rule-messages.yml, packages/eslint-plugin-slds/test/rules/lwc-token-to-slds-hook.test.js, yarn.lock
NEW: README update to include lwc-token-to-slds-hook in external
Fix: url update for hardcoded values slds2
=> 1.0.2 external patch release

packages/cli/package.json, packages/eslint-plugin-slds/package.json, yarn.lock
=> Release 1.0.2
